# Generated by Django 5.1.6 on 2025-02-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('computer_science', 'Computer Science'), ('mathematics', 'Mathematics'), ('physics', 'Physics'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('engineering', 'Engineering'), ('medicine', 'Medicine'), ('psychology', 'Psychology'), ('sociology', 'Sociology'), ('literature', 'Literature'), ('history', 'History'), ('philosophy', 'Philosophy'), ('art', 'Art'), ('economics', 'Economics'), ('law', 'Law'), ('education', 'Education'), ('linguistics', 'Linguistics')], verbose_name='status name')),
            ],
            options={
                'verbose_name': 'category',
            },
        ),
    ]
