# Generated by Django 5.1.6 on 2025-03-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('institution_type', models.CharField(choices=[('university', 'University'), ('college', 'College'), ('company', 'Company'), ('other', 'Other')], max_length=20, verbose_name='institution type')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'institution',
                'verbose_name_plural': 'institutions',
            },
        ),
    ]
