# Generated by Django 5.1.6 on 2025-02-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(choices=[('student', 'Student'), ('graduate', 'Graduate'), ('phd', 'PhD'), ('assistant_professor', 'Assistant Professor'), ('associate_professor', 'Associate Professor'), ('professor', 'Professor'), ('emeritus_professor', 'Emeritus Professor'), ('researcher', 'Researcher'), ('lecturer', 'Lecturer')], verbose_name='status name')),
            ],
            options={
                'verbose_name': 'status',
            },
        ),
    ]
