# Generated by Django 5.1.6 on 2025-02-08 15:22

import common.mixins.TimestampMixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=255, verbose_name='work name')),
                ('work_rating', models.IntegerField(verbose_name='work rating')),
                ('uniquenes_score', models.IntegerField(verbose_name='uniquenes score')),
            ],
            options={
                'verbose_name': 'scientyfic work',
            },
            bases=(common.mixins.TimestampMixins.TimestapmMixin, models.Model),
        ),
    ]
