# Generated by Django 5.1.6 on 2025-03-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'status', 'verbose_name_plural': 'statuses'},
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[('user', 'User'), ('student', 'Student'), ('graduate', 'Graduate'), ('phd', 'PhD'), ('assistant_professor', 'Assistant Professor'), ('associate_professor', 'Associate Professor'), ('professor', 'Professor'), ('emeritus_professor', 'Emeritus Professor'), ('researcher', 'Researcher'), ('lecturer', 'Lecturer')], verbose_name='status name'),
        ),
    ]
