# Generated by Django 5.1.6 on 2025-05-26 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
        ('scientific_work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scientificwork',
            options={'verbose_name': 'scientific work'},
        ),

        migrations.AddField(
            model_name='scientificwork',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='conference_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='conference name'),
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='count',
            field=models.IntegerField(default=1, verbose_name='count'),
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='date_edit',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date edited'),
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='date_publish',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='kafedra_id',
            field=models.IntegerField(default=0, verbose_name='kafedra ID'),
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='language_id',
            field=models.IntegerField(default=1, verbose_name='language ID'),
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='material_direction_dictionary_id',
            field=models.IntegerField(default=0, verbose_name='material direction dictionary ID'),
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='material_direction_id',
            field=models.IntegerField(default=0, verbose_name='material direction ID'),
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='name_jurnal',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='journal name'),
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='pub_place_id',
            field=models.IntegerField(default=0, verbose_name='publication place ID'),
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='user_d',
            field=models.IntegerField(default=0, verbose_name='user D'),
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='user ID'),
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='user_k',
            field=models.IntegerField(default=0, verbose_name='user K'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='uniquenes_score',
            field=models.IntegerField(null=True, verbose_name='uniquenes score'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='work_rating',
            field=models.IntegerField(null=True, verbose_name='work rating'),
        ),
    ]
