# Generated by Django 5.1.6 on 2025-03-13 05:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_work', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientificwork',
            name='author',
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='author',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
