# Generated by Django 5.1.6 on 2025-03-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_work', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scientificwork',
            options={'verbose_name': 'scientific work'},
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='conference_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='conference name'),
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='count',
            field=models.IntegerField(default=1, verbose_name='count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='date_add',
            field=models.DateTimeField(default=1, verbose_name='date added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='date_edit',
            field=models.DateTimeField(default=1, verbose_name='date edited'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='date_publish',
            field=models.DateField(default=1, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='file_path',
            field=models.CharField(default=1, max_length=500, verbose_name='file path'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='kafedra_id',
            field=models.IntegerField(default=1, verbose_name='kafedra ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='language_id',
            field=models.IntegerField(default=1, verbose_name='language ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='material_direction_dictionary_id',
            field=models.IntegerField(default=1, verbose_name='material direction dictionary ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='material_direction_id',
            field=models.IntegerField(default=1, verbose_name='material direction ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='name_jurnal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='journal name'),
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='pub_place_id',
            field=models.IntegerField(default=1, verbose_name='publication place ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='status',
            field=models.IntegerField(default=1, verbose_name='status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='user_d',
            field=models.IntegerField(default=1, verbose_name='user D'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='user ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='user_k',
            field=models.IntegerField(default=1, verbose_name='user K'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='uniquenes_score',
            field=models.IntegerField(verbose_name='uniqueness score'),
        ),
    ]
