# Generated by Django 5.1.6 on 2025-03-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_work', '0003_remove_scientificwork_author_scientificwork_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificwork',
            name='material_work_id',
            field=models.IntegerField(default=0, verbose_name='materia work id'),
            preserve_default=False,
        ),
    ]
