# Generated by Django 5.1.6 on 2025-03-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_work', '0003_alter_scientificwork_options_scientificwork_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificwork',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='conference_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='conference name'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='count',
            field=models.IntegerField(default=1, verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='date edited'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='date_publish',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='file_path',
            field=models.CharField(default='', max_length=500, verbose_name='file path'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='kafedra_id',
            field=models.IntegerField(default=0, verbose_name='kafedra ID'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='language_id',
            field=models.IntegerField(default=1, verbose_name='language ID'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='material_direction_dictionary_id',
            field=models.IntegerField(default=0, verbose_name='material direction dictionary ID'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='material_direction_id',
            field=models.IntegerField(default=0, verbose_name='material direction ID'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='name_jurnal',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='journal name'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='pub_place_id',
            field=models.IntegerField(default=0, verbose_name='publication place ID'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='status',
            field=models.IntegerField(default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='user_d',
            field=models.IntegerField(default=0, verbose_name='user D'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='user ID'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='user_k',
            field=models.IntegerField(default=0, verbose_name='user K'),
        ),
    ]
