# Generated by Django 5.1.6 on 2025-03-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_work', '0004_scientificwork_material_work_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificwork',
            name='file_path',
            field=models.ImageField(default='', upload_to='uploads/', verbose_name='file path'),
            preserve_default=False,
        ),
    ]
