# Generated by Django 5.1.6 on 2025-05-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_work', '0005_scientificwork_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificwork',
            name='date_of_publish',
            field=models.DateField(blank=True, null=True, verbose_name='date of publish'),
        ),
    ]
