# Generated by Django 5.1.6 on 2025-05-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_work', '0006_scientificwork_date_of_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificwork',
            name='conferenc_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='conferenc name'),
        ),
    ]
