# Generated by Django 5.1.6 on 2025-03-09 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '__first__'),
        ('users', '0002_alter_user_rating_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='institution.institution', verbose_name='status'),
        ),
    ]
