# Generated by Django 5.1.6 on 2025-03-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar_alter_user_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.CharField(default='', max_length=80, verbose_name='degree'),
            preserve_default=False,
        ),
    ]
