# Generated by Django 5.1.6 on 2025-03-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='material_user_id',
            field=models.CharField(default=0, verbose_name='material user id'),
            preserve_default=False,
        ),
    ]
