# Generated by Django 5.1.6 on 2025-03-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_material_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='scientific_work',
        ),
    ]
