# Generated by Django 5.1.6 on 2025-05-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_scientific_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(max_length=255, null=True, verbose_name='patronymic'),
        ),
    ]
