services:
  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dick69          # ⬅️ новый пароль
      MYSQL_DATABASE: science_material     # ⬅️ база под Django
    ports: ["3306:3306"]
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
